"""Market Size & Market Share Analytics Service.

Menghitung kalkulasi ukuran pasar (TAM, SAM, SOM), pangsa pasar (Market Share),
analisis musiman penjualan (Seasonality), dan simulasi skenario ekspansi bisnis (What-If)
berdasarkan database 8.559 Master Organization dan data riil finansial Syamanah 2026.
"""

from typing import Dict, Any, List, Optional
from sqlalchemy import func, or_
from app.extensions import db
from app.models import Organization

# Data Historis Omzet Riil Syamanah Group Tahun 2026 (Januari - September)
REVENUE_DATA_2026 = [
    {"month": "Jan", "month_name": "Januari", "syamanah": 3549995160, "raffiz": 3505000, "total": 3553500160},
    {"month": "Feb", "month_name": "Februari", "syamanah": 2359850634, "raffiz": 63124997, "total": 2422975631},
    {"month": "Mar", "month_name": "Maret", "syamanah": 1449766169, "raffiz": 30291000, "total": 1480057169},
    {"month": "Apr", "month_name": "April", "syamanah": 2884332833, "raffiz": 79345000, "total": 2963677833},
    {"month": "Mei", "month_name": "Mei", "syamanah": 2926200149, "raffiz": 86125000, "total": 3012325149},
    {"month": "Jun", "month_name": "Juni", "syamanah": 2429591470, "raffiz": 38665000, "total": 2468256470},
    {"month": "Jul", "month_name": "Juli", "syamanah": 4895899812, "raffiz": 46620000, "total": 4942519812},
    {"month": "Ags", "month_name": "Agustus", "syamanah": 3902716690, "raffiz": 56485000, "total": 3959201690},
    {"month": "Sep", "month_name": "September", "syamanah": 4322103455, "raffiz": 46955000, "total": 4369058455},
]

# Matriks Harga Produk Syamanah
PRODUCT_PRICING = {
    "jersey": {
        "name": "Jersey / Teamwear",
        "category": "Olahraga & Komunitas",
        "min_price": 50000,
        "max_price": 150000,
        "median_price": 100000,
        "description": "Custom jersey futsal, basket, running, esport sublimasi penuh"
    },
    "kemeja": {
        "name": "Kemeja (Kerja / PDH / PDL)",
        "category": "Korporat & Instansi",
        "min_price": 170000,
        "max_price": 170000,
        "median_price": 170000,
        "description": "Kemeja drill/tropical seragam kerja kantor, PDH harian, PDL lapangan"
    },
    "polo": {
        "name": "Polo Shirt",
        "category": "Smart Casual & Event",
        "min_price": 120000,
        "max_price": 120000,
        "median_price": 120000,
        "description": "Polo shirt bordir lacoste pique untuk gathering dan seragam santai"
    },
    "jaket": {
        "name": "Jaket (Lapangan / Bomber)",
        "category": "Outerwear & Merchandise",
        "min_price": 285000,
        "max_price": 500000,
        "median_price": 392500,
        "description": "Jaket bomber, jaket parasut lapangan, jaket varsity, dan parka"
    },
}

# Rata-rata belanja seragam per orang per tahun per sektor (dalam Rupiah)
SECTOR_SPEND_PER_PERSON = {
    "perusahaan": 340000,    # 2 stel kemeja kerja/wearpack @ Rp 170.000
    "manufaktur": 340000,    # 2 stel wearpack/baju kerja @ Rp 170.000
    "pendidikan": 290000,    # 1 seragam/almamater (170k) + 1 polo/kaos (120k)
    "mahasiswa": 220000,     # 1 kemeja/PDH organisasi (170k) + 1 jersey/kaos
    "komunitas": 200000,     # 2 pcs jersey olahraga @ Rp 100.000
    "sme_general": 200000,   # 1-2 pcs polo/kemeja
    "default": 280000,       # Blended average (~2 pcs @ Rp 140.000)
}

# Data Riset Lanskap Pasar Digital & Institusional 30 Hari Terakhir (PDF Data + Syamanah 2026)
# Berdasarkan dokumen resmi 'market share dan market size 30 Hari Terakhir.pdf' dan data finansial Syamanah 2026.
B2B_BENCHMARK_DATA = {'b2b_macro': {'annual_projected_rp': 28104000000000,
               'avg_monthly_per_producer': 2755000000,
               'channels': {'digital_catalog_pct': 33.0,
                            'dominant_traffic': 'Direct B2B Tender (52%) & Digital Catalog / Web (33%)',
                            'referral_pct': 15.0,
                            'tender_direct_pct': 52.0},
               'highlight': 'Pasar pengadaan pakaian seragam korporat, BUMN, instansi pemerintah, almamater kampus, '
                            'dan jersey komunitas di seluruh Indonesia.',
               'market_size_formatted': 'Rp 2.342 Miliar / bulan (Rp 2,34 Triliun)',
               'market_size_monthly_rp': 2342000000000,
               'org_clients_count': 8559,
               'sales_strategy': {'b2b_contract_pct': 65.0,
                                  'custom_order_pct': 25.0,
                                  'highlight': '65% transaksi garmen B2B digerakkan kontrak pengadaan institusi, 25% '
                                               'pesanan custom komunitas/klub.',
                                  'retail_merch_pct': 10.0},
               'title': 'Pasar Industri Garmen, Konveksi & Pengadaan B2B Apparel Indonesia',
               'top_10_share_pct': 31.2,
               'top_5_share_pct': 18.5,
               'total_producers_count': 850},
 'jaket': {'annual_projected_rp': 2251200000000,
           'market_size_formatted': 'Rp 187,6 Miliar / bulan',
           'market_size_monthly_rp': 187600000000,
           'title': 'Pabrik Garmen Jaket Bomber, Parka Lapangan & Outerwear B2B',
           'top_sellers': [{'avg_price': 350000,
                            'badge': 'Konglomerasi Garmen & Outerwear',
                            'city': 'Tangerang / Boyolali',
                            'monthly_rev': 8500000000,
                            'procurement_model': 'Jaket Ekspor, Outerwear Korporat Skala Besar',
                            'rank': 1,
                            'sales_channels': ['Website Resmi', 'Tender Institusi'],
                            'share_pct': 4.53,
                            'shop_name': 'PT Pan Brothers Tbk',
                            'social_handle': '@panbrothers_tbk',
                            'social_url': 'https://www.instagram.com/panbrothers_tbk/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://www.panbrotherstbk.com/'},
                           {'avg_price': 320000,
                            'badge': 'Tekstil & Garmen Terpadu',
                            'city': 'Sukoharjo, Jawa Tengah',
                            'monthly_rev': 4200000000,
                            'procurement_model': 'Jaket Kerja Perusahaan, Seragam Pabrikasi',
                            'rank': 2,
                            'sales_channels': ['Website Resmi', 'Tender B2B'],
                            'share_pct': 2.24,
                            'shop_name': 'PT Dan Liris',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://danliris.com/'},
                           {'avg_price': 392500,
                            'badge': '🥉 Top 3 Nasional: Jaket B2B & Kampus',
                            'city': 'Bandung, Jawa Barat',
                            'is_syamanah': True,
                            'monthly_rev': 3242000000,
                            'procurement_model': 'Jaket Bomber Korporat, Parka Lapangan & Varsity Kampus',
                            'rank': 3,
                            'sales_channels': ['Website Resmi', 'WhatsApp Tender', 'Instagram'],
                            'share_pct': 1.73,
                            'shop_name': 'SYAMANAH GROUP (Syamanah Apparel)',
                            'social_handle': '@syamanahjacket',
                            'social_url': 'https://www.instagram.com/syamanahjacket/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://syamanah.com/'},
                           {'avg_price': 340000,
                            'badge': 'Pabrik Apparel & Jaket Korporat',
                            'city': 'Bogor, Jawa Barat',
                            'monthly_rev': 2500000000,
                            'procurement_model': 'Jaket Perusahaan, Rompi Proyek, Tas & Merchandise B2B',
                            'rank': 4,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 1.33,
                            'shop_name': 'PT Boogie Apparel Indonesia',
                            'social_handle': '@boogieapparel',
                            'social_url': 'https://www.instagram.com/boogieapparel/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://boogie.co.id/'},
                           {'avg_price': 310000,
                            'badge': 'Vendor Jaket Instansi e-Katalog',
                            'city': 'Bandung, Jawa Barat',
                            'monthly_rev': 2100000000,
                            'procurement_model': 'Jaket Bomber Instansi, Parka & Windbreaker Dinas',
                            'rank': 5,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 1.12,
                            'shop_name': 'PT Garmenesia Prosper Mandiri',
                            'social_handle': '@garmenesia',
                            'social_url': 'https://www.instagram.com/garmenesia/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://garmenesia.co.id/'},
                           {'avg_price': 295000,
                            'badge': 'Pabrik Jaket Varsity & Bomber',
                            'city': 'Jakarta / Bandung',
                            'monthly_rev': 1900000000,
                            'procurement_model': 'Jaket Bomber Kantor, Varsity Komunitas & Hoodie Event',
                            'rank': 6,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 1.01,
                            'shop_name': 'Bikin-Baju.com (PT Bikin Baju Indonesia)',
                            'social_handle': '@official.bikinbaju',
                            'social_url': 'https://www.instagram.com/official.bikinbaju/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://bikin-baju.com/'},
                           {'avg_price': 280000,
                            'badge': 'Konveksi Jaket Angkatan & Kampus',
                            'city': 'DI Yogyakarta',
                            'monthly_rev': 1600000000,
                            'procurement_model': 'Jaket Parka, Varsity Angkatan Kampus & Jaket Coach',
                            'rank': 7,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.85,
                            'shop_name': 'Ozza Konveksi',
                            'social_handle': '@ozza.konveksi',
                            'social_url': 'https://www.instagram.com/ozza.konveksi/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://ozzakonveksi.com/'},
                           {'avg_price': 285000,
                            'badge': 'Pabrik Jaket Lapangan & Bomber',
                            'city': 'Bandung, Jawa Barat',
                            'monthly_rev': 1500000000,
                            'procurement_model': 'Jaket Parasut Taslan, Rompi & Parka Instansi',
                            'rank': 8,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.8,
                            'shop_name': 'Green Garment Indonesia',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://greengarment.id/'},
                           {'avg_price': 290000,
                            'badge': 'Konveksi Garmen Jaket Korporat',
                            'city': 'Surabaya, Jawa Timur',
                            'monthly_rev': 1400000000,
                            'procurement_model': 'Jaket Bomber Kantor, Semi Parka & Jaket Komunitas',
                            'rank': 9,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.75,
                            'shop_name': 'Vido Garment',
                            'social_handle': '@vidogarment',
                            'social_url': 'https://www.instagram.com/vidogarment/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://vidogarment.com/'},
                           {'avg_price': 285000,
                            'badge': 'Pabrik Jaket & Seragam Surabaya',
                            'city': 'Surabaya, Jawa Timur',
                            'monthly_rev': 1300000000,
                            'procurement_model': 'Jaket Outdoor, Windbreaker & Rompi Proyek',
                            'rank': 10,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.69,
                            'shop_name': 'Weva Garment',
                            'social_handle': '@wevagarment',
                            'social_url': 'https://www.instagram.com/wevagarment/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://wevagarment.com/'},
                           {'avg_price': 275000,
                            'badge': 'Konveksi Jaket Perusahaan',
                            'city': 'Bandung, Jawa Barat',
                            'monthly_rev': 1150000000,
                            'procurement_model': 'Jaket Drill, Semi Parka & Jaket Komunitas',
                            'rank': 11,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.61,
                            'shop_name': 'Konveksi Bandung Jaya',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://www.konveksibandungjaya.com/'},
                           {'avg_price': 295000,
                            'badge': 'Pabrik Jaket Safety & Lapangan',
                            'city': 'Semarang, Jawa Tengah',
                            'monthly_rev': 1050000000,
                            'procurement_model': 'Jaket Lapangan Pertambangan, Rompi Safety & Windbreaker',
                            'rank': 12,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.56,
                            'shop_name': 'Harmas Konveksi',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://harmas.co.id/'},
                           {'avg_price': 270000,
                            'badge': 'Pabrik Jaket Semi Garment',
                            'city': 'DI Yogyakarta',
                            'monthly_rev': 950000000,
                            'procurement_model': 'Jaket Varsity, Parka & Jaket Coach Mahasiswa',
                            'rank': 13,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.51,
                            'shop_name': 'Indokonveksi',
                            'social_handle': '@indokonveksi',
                            'social_url': 'https://www.instagram.com/indokonveksi/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://indokonveksi.id/'},
                           {'avg_price': 265000,
                            'badge': 'Vendor Jaket Angkatan Jogja',
                            'city': 'DI Yogyakarta',
                            'monthly_rev': 900000000,
                            'procurement_model': 'Jaket Angkatan Kampus, Komunitas & Event',
                            'rank': 14,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.48,
                            'shop_name': 'Jogja Konveksi',
                            'social_handle': '@jogjakonveksi',
                            'social_url': 'https://www.instagram.com/jogjakonveksi/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://jogjakonveksi.com/'},
                           {'avg_price': 275000,
                            'badge': 'Konveksi Jaket & Seragam Jatim',
                            'city': 'Surabaya, Jawa Timur',
                            'monthly_rev': 850000000,
                            'procurement_model': 'Jaket Bomber Kantor, Jaket Parka & Rompi Safety',
                            'rank': 15,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.45,
                            'shop_name': 'NVN Konveksi',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://nvnkonveksi.com/'},
                           {'avg_price': 270000,
                            'badge': 'Pusat Produksi Jaket B2B',
                            'city': 'Bandung, Jawa Barat',
                            'monthly_rev': 800000000,
                            'procurement_model': 'Jaket Parasut, Bomber Komunitas & Windproof',
                            'rank': 16,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.43,
                            'shop_name': 'Pusat Konveksi',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://pusatkonveksi.com/'},
                           {'avg_price': 280000,
                            'badge': 'Vendor Jaket Perusahaan Jakarta',
                            'city': 'Jakarta Selatan',
                            'monthly_rev': 750000000,
                            'procurement_model': 'Jaket Perusahaan, Komunitas Korporat & Event',
                            'rank': 17,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.4,
                            'shop_name': 'Mitra Konveksi',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://mitrakonveksi.com/'},
                           {'avg_price': 285000,
                            'badge': 'Garmen Jaket Korporat Jakarta',
                            'city': 'Jakarta Barat',
                            'monthly_rev': 700000000,
                            'procurement_model': 'Jaket Kantor, Jaket Komunitas & Seragam Kerja',
                            'rank': 18,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.37,
                            'shop_name': 'Konveksi Jakarta',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://konveksijakarta.com/'},
                           {'avg_price': 270000,
                            'badge': 'Konveksi Jaket Spesialis Bandung',
                            'city': 'Bandung, Jawa Barat',
                            'monthly_rev': 650000000,
                            'procurement_model': 'Jaket Angkatan, Bomber Taslan & Fleece',
                            'rank': 19,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.35,
                            'shop_name': 'Konveksi Bandung ID',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://konveksibandung.id/'},
                           {'avg_price': 275000,
                            'badge': 'Apparel Komunitas Nasional',
                            'city': 'Jakarta Selatan',
                            'monthly_rev': 600000000,
                            'procurement_model': 'Jaket Merchandise, Parka Event & Gathering',
                            'rank': 20,
                            'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                            'share_pct': 0.32,
                            'shop_name': 'Rumah Komunitas Outerwear',
                            'social_handle': '@rumahkomunitas.id',
                            'social_url': 'https://www.instagram.com/rumahkomunitas.id/',
                            'store_name': 'Web Resmi',
                            'store_url': 'https://rumahkomunitas.com/'}]},
 'jersey': {'annual_projected_rp': 780000000000,
            'b2b_players_count': 180,
            'channels': {'direct_tender_pct': 52.0,
                         'live_pct': 32.1,
                         'mall_pct': 18.0,
                         'referral_agent_pct': 15.0,
                         'video_pct': 49.9,
                         'web_catalog_pct': 33.0},
            'layer_hierarchy': [{'category': 'Apparel Olahraga & Event Nasional',
                                 'layer': 'Layer 1',
                                 'monthly_rp': 548500000000,
                                 'share_pct': 100.0,
                                 'stores': 1250},
                                {'category': 'Seragam Olahraga & Teamwear Institusi',
                                 'layer': 'Layer 2',
                                 'monthly_rp': 182700000000,
                                 'share_pct': 33.3,
                                 'stores': 450},
                                {'category': 'Pabrik Printing Sublimasi Custom (Jersey)',
                                 'layer': 'Layer 3',
                                 'monthly_rp': 65000000000,
                                 'share_pct': 11.8,
                                 'stores': 180}],
            'market_size_formatted': 'Rp 65,0 Miliar / bulan',
            'market_size_monthly_rp': 65000000000,
            'price_segments': [{'is_syamanah': False,
                                'monthly_val': 17764500000,
                                'share_pct': 27.33,
                                'status': 'Partai massal kampanye / event promosi murah (kain pe/hyget)',
                                'tier': '< Rp 50.000 (Low-End / Partai Sablon)'},
                               {'is_syamanah': True,
                                'monthly_val': 26988000000,
                                'share_pct': 41.52,
                                'status': 'Sweet Spot Syamanah: Komunitas olahraga, futsal, running & event',
                                'tier': 'Rp 50.000 - Rp 100.000 (Mid-Range Komunitas)'},
                               {'is_syamanah': True,
                                'monthly_val': 13747500000,
                                'share_pct': 21.15,
                                'status': 'Jersey Institusi B2B & Klub Liga (Kain dri-fit premium + anti-bakteri)',
                                'tier': 'Rp 100.000 - Rp 150.000 (Premium Sublimasi B2B)'},
                               {'is_syamanah': False,
                                'monthly_val': 6500000000,
                                'share_pct': 10.0,
                                'status': 'Jersey official apparel atletik profesional & edisi kolektor terbatas',
                                'tier': '> Rp 150.000 (High-End Pro / Authentic)'}],
            'title': 'Pabrik & Vendor Jersey Printing Sublimasi Olahraga (B2B & Komunitas)',
            'top_sellers': [{'avg_price': 56000,
                             'badge': 'Pabrik Jersey Custom & Sublimasi Terbesar',
                             'city': 'Wonogiri, Jawa Tengah',
                             'monthly_rev': 4800000000,
                             'procurement_model': 'Jersey Futsal, Voli, Sepeda & Komunitas Nasional',
                             'rank': 1,
                             'sales_channels': ['Website Resmi', 'Jaringan Reseller'],
                             'share_pct': 7.38,
                             'shop_name': 'PT Regar Sport Industri (Regarsport)',
                             'social_handle': '@regarsportofficial',
                             'social_url': 'https://www.instagram.com/regarsportofficial/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://regarsport.com/',
                             'volume': '85.000+ pcs'},
                            {'avg_price': 101300,
                             'badge': '🥈 Top 2 Nasional: Jersey Sublimasi B2B',
                             'city': 'Bandung, Jawa Barat',
                             'is_syamanah': True,
                             'monthly_rev': 3242000000,
                             'procurement_model': 'Jersey Sublimasi Tim, Komunitas, Event & B2B Kustom',
                             'rank': 2,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS', 'Instagram'],
                             'share_pct': 4.99,
                             'shop_name': 'SYAMANAH GROUP (Syamanah Apparel)',
                             'social_handle': '@syamanahjersey',
                             'social_url': 'https://www.instagram.com/syamanahjersey/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://syamanah.com/',
                             'volume': '32.000+ pcs'},
                            {'avg_price': 95000,
                             'badge': 'Pabrik Sublimasi Futsal & Sepeda',
                             'city': 'Surakarta, Jawa Tengah',
                             'monthly_rev': 2100000000,
                             'procurement_model': 'Jersey Futsal, Sepeda, Running & Gaming',
                             'rank': 3,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 3.23,
                             'shop_name': 'Garuda Print Solo (PT Garuda Printing)',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://www.garudaprint.com/',
                             'volume': '22.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Pabrik Jersey Komunitas & Klub',
                             'city': 'Surakarta, Jawa Tengah',
                             'monthly_rev': 1700000000,
                             'procurement_model': 'Jersey Printing Komunitas, Klub & Sekolah',
                             'rank': 4,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 2.62,
                             'shop_name': 'Sintesa Konveksi',
                             'social_handle': '@sintesakonveksi',
                             'social_url': 'https://www.instagram.com/sintesakonveksi/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://sintesakonveksi.com/',
                             'volume': '17.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Vendor Jersey Jabodetabek',
                             'city': 'Bekasi / Jakarta',
                             'monthly_rev': 1400000000,
                             'procurement_model': 'Jersey Esport, Futsal & Komunitas Korporat',
                             'rank': 5,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 2.15,
                             'shop_name': 'Vendor Jersey (VR Apparel)',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://vendorjersey.com/',
                             'volume': '14.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Spesialis Jersey Printing Sublim',
                             'city': 'DI Yogyakarta',
                             'monthly_rev': 1200000000,
                             'procurement_model': 'Jersey Futsal, Basket, Running & Badminton',
                             'rank': 6,
                             'sales_channels': ['Website Resmi', 'Instagram'],
                             'share_pct': 1.85,
                             'shop_name': 'Zeta Apparel',
                             'social_handle': '@zetaapparel',
                             'social_url': 'https://www.instagram.com/zetaapparel/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://zetaapparel.com/',
                             'volume': '12.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Produsen Jersey Sublimasi Jogja',
                             'city': 'DI Yogyakarta',
                             'monthly_rev': 1050000000,
                             'procurement_model': 'Jersey Sepakbola, Futsal & Komunitas Gowes',
                             'rank': 7,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.62,
                             'shop_name': 'Maestro Jersey',
                             'social_handle': '@maestrojersey',
                             'social_url': 'https://www.instagram.com/maestrojersey/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://maestrojersey.com/',
                             'volume': '10.500+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Vendor Jersey Custom Bandung',
                             'city': 'Bandung, Jawa Barat',
                             'monthly_rev': 950000000,
                             'procurement_model': 'Jersey Motocross, Sepeda, Mancing & Event',
                             'rank': 8,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.46,
                             'shop_name': 'Jersey Keren Bandung',
                             'social_handle': '@jerseykeren',
                             'social_url': 'https://www.instagram.com/jerseykeren/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://jerseykeren.com/',
                             'volume': '9.500+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Apparel & Jersey Komunitas',
                             'city': 'Jakarta / Bandung',
                             'monthly_rev': 900000000,
                             'procurement_model': 'Apparel Gathering, Komunitas Olahraga & Kaos Event',
                             'rank': 9,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.38,
                             'shop_name': 'Rumah Komunitas',
                             'social_handle': '@rumahkomunitas.id',
                             'social_url': 'https://www.instagram.com/rumahkomunitas.id/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://rumahkomunitas.com/',
                             'volume': '9.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Pabrikasi Custom Sublimasi',
                             'city': 'Jakarta Selatan',
                             'monthly_rev': 850000000,
                             'procurement_model': 'Jersey Klub Liga Amatir, Turnamen & Kantor',
                             'rank': 10,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.31,
                             'shop_name': 'Custom Jersey ID',
                             'social_handle': '@customjersey',
                             'social_url': 'https://www.instagram.com/customjersey/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://customjersey.id/',
                             'volume': '8.500+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Spesialis Jersey Sublim Jabodetabek',
                             'city': 'Jakarta / Tangerang',
                             'monthly_rev': 800000000,
                             'procurement_model': 'Jersey Futsal Kantor, Gowes & Basket',
                             'rank': 11,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.23,
                             'shop_name': 'Bikin Jersey Jakarta',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://bikinjersey.com/',
                             'volume': '8.000+ pcs'},
                            {'avg_price': 94000,
                             'badge': 'Pabrik Kostum Futsal & Sepakbola',
                             'city': 'Surabaya, Jawa Timur',
                             'monthly_rev': 750000000,
                             'procurement_model': 'Kostum Futsal, Sepakbola & Rompi Latihan',
                             'rank': 12,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.15,
                             'shop_name': 'Kaos Futsal Net',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://kaosfutsal.net/',
                             'volume': '8.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Print Sublimasi Full Color',
                             'city': 'Jakarta Timur',
                             'monthly_rev': 700000000,
                             'procurement_model': 'Printing Sublim Tekstil, Jersey Motocross & Sepeda',
                             'rank': 13,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.08,
                             'shop_name': 'Print Jersey',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://printjersey.com/',
                             'volume': '7.000+ pcs'},
                            {'avg_price': 95000,
                             'badge': 'Konveksi Jersey Olahraga Massal',
                             'city': 'Solo, Jawa Tengah',
                             'monthly_rev': 650000000,
                             'procurement_model': 'Jersey Printing Komunitas, Futsal & Sekolah',
                             'rank': 14,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 1.0,
                             'shop_name': 'Konveksi Jersey',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://konveksijersey.com/',
                             'volume': '6.800+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Divisi Sportswear & Sublimasi',
                             'city': 'DI Yogyakarta',
                             'monthly_rev': 600000000,
                             'procurement_model': 'Jersey Angkatan, Komunitas Olahraga Kampus',
                             'rank': 15,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 0.92,
                             'shop_name': 'Ozza Konveksi (Lini Jersey)',
                             'social_handle': '@ozza.konveksi',
                             'social_url': 'https://www.instagram.com/ozza.konveksi/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://ozzakonveksi.com/',
                             'volume': '6.000+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Pabrik Konveksi Semi Garmen',
                             'city': 'DI Yogyakarta',
                             'monthly_rev': 580000000,
                             'procurement_model': 'Jersey Komunitas Olahraga, Running & Event',
                             'rank': 16,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 0.89,
                             'shop_name': 'Indokonveksi (Lini Sportswear)',
                             'social_handle': '@indokonveksi',
                             'social_url': 'https://www.instagram.com/indokonveksi/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://indokonveksi.id/',
                             'volume': '5.800+ pcs'},
                            {'avg_price': 100000,
                             'badge': 'Konveksi Apparel Olahraga',
                             'city': 'DI Yogyakarta',
                             'monthly_rev': 550000000,
                             'procurement_model': 'Jersey Event Olahraga, Futsal & Voli',
                             'rank': 17,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 0.85,
                             'shop_name': 'Jogja Konveksi',
                             'social_handle': '@jogjakonveksi',
                             'social_url': 'https://www.instagram.com/jogjakonveksi/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://jogjakonveksi.com/',
                             'volume': '5.500+ pcs'},
                            {'avg_price': 104000,
                             'badge': 'Garmen Sportswear Korporat',
                             'city': 'Bandung, Jawa Barat',
                             'monthly_rev': 520000000,
                             'procurement_model': 'Jersey Event Perusahaan, BUMN & Lembaga',
                             'rank': 18,
                             'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                             'share_pct': 0.8,
                             'shop_name': 'PT Garmenesia Prosper Mandiri (Lini Sport)',
                             'social_handle': '@garmenesia',
                             'social_url': 'https://www.instagram.com/garmenesia/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://garmenesia.co.id/',
                             'volume': '5.000+ pcs'},
                            {'avg_price': 120000,
                             'badge': 'Apparel Olahraga Nasional',
                             'city': 'Jakarta Barat',
                             'monthly_rev': 500000000,
                             'procurement_model': 'Pengadaan Teamwear Klub Profesional & Korporat',
                             'rank': 19,
                             'sales_channels': ['Website Resmi', 'Kontrak Tim'],
                             'share_pct': 0.77,
                             'shop_name': 'PT Mitra Kreasi Garmen (Mills Sport B2B)',
                             'social_handle': '@millssportid',
                             'social_url': 'https://www.instagram.com/millssportid/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://mills.co.id/',
                             'volume': '4.200+ pcs'},
                            {'avg_price': 120000,
                             'badge': 'Brand Olahraga Nasional',
                             'city': 'Jakarta Utara',
                             'monthly_rev': 480000000,
                             'procurement_model': 'Custom Teamwear Futsal & Sepakbola Komersial',
                             'rank': 20,
                             'sales_channels': ['Website Resmi', 'Pengadaan Tim'],
                             'share_pct': 0.74,
                             'shop_name': 'PT Panatrade Caraka (Specs B2B)',
                             'social_handle': '@specs_indonesia',
                             'social_url': 'https://www.instagram.com/specs_indonesia/',
                             'store_name': 'Web Resmi',
                             'store_url': 'https://specs.id/',
                             'volume': '4.000+ pcs'}]},
 'national_top_brands': [{'badge': 'Konglomerasi Garmen Nasional',
                          'city': 'Tangerang / Boyolali',
                          'is_syamanah': False,
                          'main_category': 'Garmen Ekspor, Jaket & Apparel Korporat',
                          'monthly_rev': 18500000000,
                          'procurement_model': 'Garmen Apparel Skala Industri & Ekspor',
                          'rank': 1,
                          'sales_channels': ['Website Resmi', 'Tender Korporat'],
                          'share_pct': 27.2,
                          'shop_name': 'PT Pan Brothers Tbk',
                          'social_handle': '@panbrothers_tbk',
                          'social_url': 'https://www.instagram.com/panbrothers_tbk/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://www.panbrotherstbk.com/'},
                         {'badge': 'No. 1 Seragam Korporat & Kain Bellini',
                          'city': 'Jakarta / Bandung',
                          'is_syamanah': False,
                          'main_category': 'Seragam Korporat, Perbankan & BUMN',
                          'monthly_rev': 15000000000,
                          'procurement_model': 'Seragam Institusi Finansial, BUMN & Maskapai',
                          'rank': 2,
                          'sales_channels': ['Website Resmi', 'Tender BUMN'],
                          'share_pct': 22.05,
                          'shop_name': 'PT Trisula International Tbk',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://www.trisula.com/'},
                         {'badge': 'Pabrik Tekstil & Konveksi Terpadu',
                          'city': 'Sukoharjo, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Tekstil Terpadu, Seragam Kerja & Jaket',
                          'monthly_rev': 8500000000,
                          'procurement_model': 'Pabrikasi Seragam Perusahaan & Garmen Ekspor',
                          'rank': 3,
                          'sales_channels': ['Website Resmi', 'Tender Institusi'],
                          'share_pct': 12.5,
                          'shop_name': 'PT Dan Liris',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://danliris.com/'},
                         {'badge': 'Pabrik Jersey Custom Terbesar',
                          'city': 'Wonogiri, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Jersey Printing & Sublimasi Olahraga',
                          'monthly_rev': 4500000000,
                          'procurement_model': 'Pabrikasi Massal Sublimasi & Kemitraan Reseller',
                          'rank': 4,
                          'sales_channels': ['Website Resmi', 'Kemitraan Reseller'],
                          'share_pct': 6.62,
                          'shop_name': 'PT Regar Sport Industri (Regarsport)',
                          'social_handle': '@regarsportofficial',
                          'social_url': 'https://www.instagram.com/regarsportofficial/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://regarsport.net/id'},
                         {'badge': '🏆 TOP #5 NASIONAL: Produsen Terpadu B2B',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': True,
                          'main_category': 'Jersey Sublimasi, Kemeja PDH & Jaket Korporat',
                          'monthly_rev': 3242000000,
                          'procurement_model': 'Pabrikasi Terpadu B2B, Instansi Pemerintah, BUMN & Kampus',
                          'rank': 5,
                          'sales_channels': ['Website Resmi', 'WhatsApp Tender', 'Instagram'],
                          'share_pct': 4.77,
                          'shop_name': 'SYAMANAH GROUP (Syamanah + Raffiz)',
                          'social_handle': '@syamanahjersey',
                          'social_url': 'https://www.instagram.com/syamanahjersey/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://syamanah.com/'},
                         {'badge': 'Spesialis Workwear & Safety',
                          'city': 'Semarang, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Wearpack Safety, Coverall & Kemeja Pabrik',
                          'monthly_rev': 2800000000,
                          'procurement_model': 'Wearpack Safety Proyek, Coverall & Kemeja Pabrik',
                          'rank': 6,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 4.12,
                          'shop_name': 'Moko Garment Indonesia',
                          'social_handle': '@mokoworkwear',
                          'social_url': 'https://www.instagram.com/mokoworkwear/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://moko.co.id/'},
                         {'badge': 'Pabrik Konveksi Kaos & Kemeja',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': False,
                          'main_category': 'Kaos Promosi, Polo & Kemeja Seragam',
                          'monthly_rev': 2500000000,
                          'procurement_model': 'Pesanan Kaos Event, Polo Shirt & Seragam Kantor',
                          'rank': 7,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 3.68,
                          'shop_name': 'PT Amanah Garment Bandung',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://amanahgarment.co.id/'},
                         {'badge': 'Vendor Seragam e-Katalog',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': False,
                          'main_category': 'Kemeja PDH, Jaket Bomber & Rompi',
                          'monthly_rev': 1900000000,
                          'procurement_model': 'Kemeja PDH Dinas, Jaket Instansi & Tender Pemerintah',
                          'rank': 8,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 2.79,
                          'shop_name': 'PT Garmenesia Apparel Indonesia',
                          'social_handle': '@garmenesia',
                          'social_url': 'https://www.instagram.com/garmenesia/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://garmenesia.co.id/'},
                         {'badge': 'Pabrik Sublimasi Futsal & Sepeda',
                          'city': 'Solo, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Jersey Printing Futsal, Sepeda & Esport',
                          'monthly_rev': 1800000000,
                          'procurement_model': 'Jersey Sublimasi Futsal, Sepeda & Running',
                          'rank': 9,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 2.65,
                          'shop_name': 'Garuda Print (PT Garuda Printing)',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://www.garudaprint.com/'},
                         {'badge': 'Vendor Seragam Korporat Jakarta',
                          'city': 'Jakarta Barat, DKI Jakarta',
                          'is_syamanah': False,
                          'main_category': 'Seragam Kerja Kantor & Corporate Event',
                          'monthly_rev': 1600000000,
                          'procurement_model': 'Seragam Perusahaan Swasta, BUMN & Event',
                          'rank': 10,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 2.35,
                          'shop_name': 'Bikin-Baju.com (PT Bikin Baju)',
                          'social_handle': '@official.bikinbaju',
                          'social_url': 'https://www.instagram.com/official.bikinbaju/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://bikin-baju.com/'},
                         {'badge': 'Pabrik Jaket & Rompi B2B',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': False,
                          'main_category': 'Jaket Lapangan, Rompi & Kemeja PDL',
                          'monthly_rev': 1500000000,
                          'procurement_model': 'Jaket Taslan, Rompi Proyek & Seragam Lapangan',
                          'rank': 11,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 2.2,
                          'shop_name': 'Green Garment Indonesia',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://greengarment.id/'},
                         {'badge': 'Pabrik Jersey Komunitas',
                          'city': 'Solo, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Jersey Printing Olahraga & Kaos Komunitas',
                          'monthly_rev': 1400000000,
                          'procurement_model': 'Jersey Printing Komunitas, Klub & Sekolah',
                          'rank': 12,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 2.06,
                          'shop_name': 'Sintesa Konveksi',
                          'social_handle': '@sintesakonveksi',
                          'social_url': 'https://www.instagram.com/sintesakonveksi/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://sintesakonveksi.com/'},
                         {'badge': 'Vendor Kampus & Universitas',
                          'city': 'Yogyakarta',
                          'is_syamanah': False,
                          'main_category': 'Jas Almamater, Seragam Kampus & PDH',
                          'monthly_rev': 1300000000,
                          'procurement_model': 'Jas Almamater Universitas, Kemeja PDH Mahasiswa & PNS',
                          'rank': 13,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.91,
                          'shop_name': 'Ozza Konveksi (PT Ozza Konveksi)',
                          'social_handle': '@ozza.konveksi',
                          'social_url': 'https://www.instagram.com/ozza.konveksi/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://ozzakonveksi.com/'},
                         {'badge': 'Konveksi Seragam Kerja',
                          'city': 'Tangerang / Jakarta',
                          'is_syamanah': False,
                          'main_category': 'Seragam Proyek, PDH Dinas & Wearpack',
                          'monthly_rev': 1200000000,
                          'procurement_model': 'Seragam Proyek, PDH Dinas & Kemeja Perusahaan',
                          'rank': 14,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.76,
                          'shop_name': 'Pabrik Seragam Indonesia',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://pabrikseragam.co.id/'},
                         {'badge': 'Vendor Jersey Custom',
                          'city': 'Jakarta / Bekasi',
                          'is_syamanah': False,
                          'main_category': 'Jersey Custom Printing Sublimasi',
                          'monthly_rev': 1100000000,
                          'procurement_model': 'Jersey Esport, Futsal & Komunitas Korporat',
                          'rank': 15,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.62,
                          'shop_name': 'Vendor Jersey (VR Apparel)',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://vendorjersey.com/'},
                         {'badge': 'Workwear Pertambangan & Safety',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': False,
                          'main_category': 'Wearpack Tambang & Rompi Safety',
                          'monthly_rev': 1000000000,
                          'procurement_model': 'Wearpack Reflektor Tambang, Rompi & Seragam Lapangan',
                          'rank': 16,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.47,
                          'shop_name': 'Konveksi Tambang',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://konveksitambang.com/'},
                         {'badge': 'Konveksi Seragam Bandung',
                          'city': 'Bandung, Jawa Barat',
                          'is_syamanah': False,
                          'main_category': 'Kemeja Drill, Seragam Kantor & Jaket',
                          'monthly_rev': 950000000,
                          'procurement_model': 'Kemeja Drill Perusahaan, Jaket & Kaos Promosi',
                          'rank': 17,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.4,
                          'shop_name': 'Konveksi Bandung Jaya',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://www.konveksibandungjaya.com/'},
                         {'badge': 'Pabrik Seragam Industri',
                          'city': 'Kudus, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Seragam Pabrik, Rumah Sakit & Wearpack',
                          'monthly_rev': 900000000,
                          'procurement_model': 'Seragam Buruh Pabrik, Wearpack & Jas Lab Rumah Sakit',
                          'rank': 18,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.32,
                          'shop_name': 'Konveksi Hasan (CV Hasan Garment)',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://konveksihasan.com/'},
                         {'badge': 'Konveksi Seragam Solo',
                          'city': 'Solo, Jawa Tengah',
                          'is_syamanah': False,
                          'main_category': 'Seragam PDH, Kaos Promosi & Jaket',
                          'monthly_rev': 850000000,
                          'procurement_model': 'Seragam Kantor, PDH Instansi & Kaos Gathering',
                          'rank': 19,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.25,
                          'shop_name': 'Spirit Konveksi',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://www.spiritkonveksi.com/'},
                         {'badge': 'Vendor Merchandise Komunitas',
                          'city': 'Bandung / Jakarta',
                          'is_syamanah': False,
                          'main_category': 'Apparel Gathering, Komunitas & Merchandise',
                          'monthly_rev': 800000000,
                          'procurement_model': 'Kaos Komunitas, Merchandise Event & Polo Gathering',
                          'rank': 20,
                          'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                          'share_pct': 1.18,
                          'shop_name': 'Rumah Komunitas',
                          'social_handle': '@rumahkomunitas.id',
                          'social_url': 'https://www.instagram.com/rumahkomunitas.id/',
                          'store_name': 'Web Resmi',
                          'store_url': 'https://rumahkomunitas.com/'}],
 'report_period': 'Lanskap Riset Pasar Garmen, Konveksi & B2B Apparel Nasional 2026',
 'seragam': {'annual_projected_rp': 1500000000000,
             'market_size_formatted': 'Rp 125,0 Miliar / bulan',
             'market_size_monthly_rp': 125000000000,
             'segments': [{'category': 'Kemeja PDH / PDL Instansi & BUMN',
                           'dominant_channel': 'Tender Pengadaan / SPK',
                           'monthly_rp': 62500000000,
                           'share_pct': 50.0},
                          {'category': 'Wearpack Safety & Pabrikasi Tambang',
                           'dominant_channel': 'Kontrak Tahunan Korporat',
                           'monthly_rp': 37500000000,
                           'share_pct': 30.0},
                          {'category': 'Jas Almamater & Seragam Pendidikan',
                           'dominant_channel': 'Tender Kampus & Sekolah',
                           'monthly_rp': 25000000000,
                           'share_pct': 20.0}],
             'title': 'Pabrik & Konveksi Seragam Kerja Kantor, PDH/PDL & Wearpack',
             'top_sellers': [{'badge': 'No. 1 Seragam Korporat & Kain Bellini',
                              'category': 'Seragam Korporat, Perbankan & BUMN',
                              'city': 'Cimahi / Jakarta',
                              'monthly_rev': 15000000000,
                              'procurement_model': 'Seragam Bank, BUMN, Rumah Sakit & Institusi Nasional',
                              'rank': 1,
                              'sales_channels': ['Website Resmi', 'Tender Nasional'],
                              'share_pct': 12.0,
                              'shop_name': 'PT Trisula International Tbk',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://www.trisula.com/'},
                             {'badge': 'Spesialis Seragam Kerja & Wearpack',
                              'category': 'Wearpack Safety, Coverall & Kemeja Pabrik',
                              'city': 'Semarang, Jawa Tengah',
                              'monthly_rev': 5500000000,
                              'procurement_model': 'Wearpack Safety Proyek, Coverall Pabrik & Kemeja Kantor',
                              'rank': 2,
                              'sales_channels': ['Website Resmi', 'WhatsApp B2B'],
                              'share_pct': 4.4,
                              'shop_name': 'Moko Garment Indonesia (PT Moko Garment)',
                              'social_handle': '@mokoworkwear',
                              'social_url': 'https://www.instagram.com/mokoworkwear/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://moko.co.id/'},
                             {'badge': 'Pabrik Konveksi Partai Besar',
                              'category': 'Kemeja PDH, Polo & Kaos Seragam Partai Besar',
                              'city': 'Bandung & Sleman',
                              'monthly_rev': 3800000000,
                              'procurement_model': 'Seragam Kerja Kantor, Kaos Polo & Kemeja PDH',
                              'rank': 3,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 3.04,
                              'shop_name': 'PT Amanah Garment',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://amanahgarment.co.id/'},
                             {'badge': '🎖️ Peringkat #4 Nasional Seragam B2B',
                              'category': 'Kemeja PDH/PDL, Seragam Pabrik & Almamater Kampus',
                              'city': 'Bandung, Jawa Barat',
                              'is_syamanah': True,
                              'monthly_rev': 3242000000,
                              'procurement_model': 'Kemeja PDH Drill, Seragam Pabrik, Almamater & Wearpack',
                              'rank': 4,
                              'sales_channels': ['Website Resmi', 'WhatsApp Tender', 'Instagram'],
                              'share_pct': 2.59,
                              'shop_name': 'SYAMANAH GROUP (Syamanah Apparel)',
                              'social_handle': '@syamanahseragam',
                              'social_url': 'https://www.instagram.com/syamanahseragam/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://syamanah.com/'},
                             {'badge': 'Garmen Pengadaan Seragam Instansi',
                              'category': 'Kemeja PDH Dinas, Wearpack & Rompi e-Katalog',
                              'city': 'Bandung, Jawa Barat',
                              'monthly_rev': 2600000000,
                              'procurement_model': 'Kemeja Dinas Pemda, Seragam BUMN & Wearpack Lapangan',
                              'rank': 5,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 2.08,
                              'shop_name': 'PT Garmenesia Prosper Mandiri',
                              'social_handle': '@garmenesia',
                              'social_url': 'https://www.instagram.com/garmenesia/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://garmenesia.co.id/'},
                             {'badge': 'Konveksi Seragam Kantor & BUMN',
                              'category': 'Seragam Kantor, PDH Dinas & Baju Proyek',
                              'city': 'Jakarta Barat',
                              'monthly_rev': 2200000000,
                              'procurement_model': 'Seragam Proyek, PDH Dinas & Kemeja Perusahaan',
                              'rank': 6,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.76,
                              'shop_name': 'Pabrik Seragam Indonesia',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://pabrikseragam.co.id/'},
                             {'badge': 'Spesialis Workwear Pertambangan',
                              'category': 'Wearpack Safety Tambang, Rompi & Flame Retardant',
                              'city': 'Bandung, Jawa Barat',
                              'monthly_rev': 1900000000,
                              'procurement_model': 'Wearpack Reflektor 3M Tambang, Rompi & Coverall Lapangan',
                              'rank': 7,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.52,
                              'shop_name': 'Konveksi Tambang',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://konveksitambang.com/'},
                             {'badge': 'Pabrik Workwear Industri',
                              'category': 'Wearpack Proyek, Seragam Pabrik & PDH Kantor',
                              'city': 'Semarang, Jawa Tengah',
                              'monthly_rev': 1750000000,
                              'procurement_model': 'Seragam Industri Manufaktur, Wearpack Proyek & Kemeja Kerja',
                              'rank': 8,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.4,
                              'shop_name': 'Konveksi Seragam Harmas',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://harmas.co.id/'},
                             {'badge': 'Vendor Seragam Perusahaan Jakarta',
                              'category': 'Kemeja Kantor, PDH & Corporate Uniform',
                              'city': 'Jakarta Barat',
                              'monthly_rev': 1600000000,
                              'procurement_model': 'Seragam Perusahaan Swasta, BUMN & Kemeja Event',
                              'rank': 9,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.28,
                              'shop_name': 'Bikin-Baju.com (PT Bikin Baju Indonesia)',
                              'social_handle': '@official.bikinbaju',
                              'social_url': 'https://www.instagram.com/official.bikinbaju/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://bikin-baju.com/'},
                             {'badge': 'Garmen Apparel & Seragam Korporat',
                              'category': 'Seragam Korporat, Rompi Lapangan & Polo Kantor',
                              'city': 'Bogor, Jawa Barat',
                              'monthly_rev': 1500000000,
                              'procurement_model': 'Kemeja Kantor Korporat, Rompi B2B & Seragam Event',
                              'rank': 10,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.2,
                              'shop_name': 'PT Boogie Apparel Indonesia',
                              'social_handle': '@boogieapparel',
                              'social_url': 'https://www.instagram.com/boogieapparel/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://boogie.co.id/'},
                             {'badge': 'Konveksi Almamater & Kampus',
                              'category': 'Jas Almamater, Seragam Kampus & PDH',
                              'city': 'DI Yogyakarta',
                              'monthly_rev': 1400000000,
                              'procurement_model': 'Jas Almamater Universitas, Kemeja PDH Mahasiswa & PNS',
                              'rank': 11,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.12,
                              'shop_name': 'Ozza Konveksi',
                              'social_handle': '@ozza.konveksi',
                              'social_url': 'https://www.instagram.com/ozza.konveksi/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://ozzakonveksi.com/'},
                             {'badge': 'Pabrik Seragam Kerja Jawa Timur',
                              'category': 'Kemeja Kerja Kantor, Wearpack & Seragam RS',
                              'city': 'Surabaya, Jawa Timur',
                              'monthly_rev': 1300000000,
                              'procurement_model': 'Seragam Kerja Kantor, Wearpack Safety & Kemeja PDH',
                              'rank': 12,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 1.04,
                              'shop_name': 'Vido Garment',
                              'social_handle': '@vidogarment',
                              'social_url': 'https://www.instagram.com/vidogarment/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://vidogarment.com/'},
                             {'badge': 'Konveksi Seragam Industri Surabaya',
                              'category': 'Seragam Pabrik, Wearpack Proyek & Kemeja PDL',
                              'city': 'Surabaya, Jawa Timur',
                              'monthly_rev': 1200000000,
                              'procurement_model': 'Wearpack Coverall, Kemeja Lapangan & Baju Kerja Industri',
                              'rank': 13,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.96,
                              'shop_name': 'Weva Garment',
                              'social_handle': '@wevagarment',
                              'social_url': 'https://www.instagram.com/wevagarment/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://wevagarment.com/'},
                             {'badge': 'Spesialis Seragam Kantor Jakarta',
                              'category': 'Kemeja Kantor Eksklusif, PDH & Batik Korporat',
                              'city': 'Jakarta Selatan',
                              'monthly_rev': 1100000000,
                              'procurement_model': 'Kemeja Drill Kantor, Baju Kerja Bank & Seragam Kantor Pemda',
                              'rank': 14,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.88,
                              'shop_name': 'Seragam Kantor ID',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://seragamkantor.id/'},
                             {'badge': 'Konveksi Seragam Pabrik & Kantor',
                              'category': 'Seragam PDH, Kemeja Pabrik & Celana Kerja',
                              'city': 'Bandung, Jawa Barat',
                              'monthly_rev': 1000000000,
                              'procurement_model': 'Kemeja Kerja Pabrik, Seragam Dinas & PDH Instansi',
                              'rank': 15,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.8,
                              'shop_name': 'Seragam Kantor COM',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://seragamkantor.com/'},
                             {'badge': 'Semi Garment Seragam Kampus',
                              'category': 'Kemeja PDH Organisasi, Kampus & Wearpack',
                              'city': 'DI Yogyakarta',
                              'monthly_rev': 920000000,
                              'procurement_model': 'Kemeja PDH Kampus, Seragam Organisasi & Komunitas',
                              'rank': 16,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.74,
                              'shop_name': 'Indokonveksi',
                              'social_handle': '@indokonveksi',
                              'social_url': 'https://www.instagram.com/indokonveksi/',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://indokonveksi.id/'},
                             {'badge': 'Konveksi Workwear B2B',
                              'category': 'Wearpack Kerja, Rompi Safety & Seragam Pabrik',
                              'city': 'Bandung, Jawa Barat',
                              'monthly_rev': 850000000,
                              'procurement_model': 'Wearpack Proyek, Rompi Lapangan & Seragam Teknisi',
                              'rank': 17,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.68,
                              'shop_name': 'Green Garment Workwear',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://greengarment.id/'},
                             {'badge': 'Pusat Pembuatan Seragam Jakarta',
                              'category': 'Seragam Kantor, Kemeja PDH & Polo Bordir',
                              'city': 'Jakarta Barat',
                              'monthly_rev': 780000000,
                              'procurement_model': 'Kemeja Kerja Perusahaan, PDH Kantor & Kaos Kerah',
                              'rank': 18,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.62,
                              'shop_name': 'Konveksi Jakarta',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://konveksijakarta.com/'},
                             {'badge': 'Konveksi Seragam Massal',
                              'category': 'Kemeja Kerja Massal, PDH & Seragam Komunitas',
                              'city': 'Bandung, Jawa Barat',
                              'monthly_rev': 720000000,
                              'procurement_model': 'Seragam Pabrik, Kemeja Komunitas & PDH Kampus',
                              'rank': 19,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.58,
                              'shop_name': 'Pusat Konveksi',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://pusatkonveksi.com/'},
                             {'badge': 'Konveksi Seragam Jawa Timur',
                              'category': 'Wearpack, Kemeja Drill & Baju Kerja Jatim',
                              'city': 'Surabaya, Jawa Timur',
                              'monthly_rev': 680000000,
                              'procurement_model': 'Seragam Kerja Teknisi, Wearpack Bengkel & Kemeja Kantor',
                              'rank': 20,
                              'sales_channels': ['Website Resmi', 'WhatsApp CS'],
                              'share_pct': 0.54,
                              'shop_name': 'NVN Konveksi Seragam',
                              'store_name': 'Web Resmi',
                              'store_url': 'https://nvnkonveksi.com/'}]},
 'syamanah_standing': {'annual_projected_formatted': 'Rp 38,90 Miliar / thn',
                       'category_ranks': [{'badge_class': 'bg-warning text-dark',
                                           'category': 'Jersey & Teamwear Olahraga',
                                           'leader': 'PT Regar Sport Industri (Rp 4,5 M/bln)',
                                           'rank': 2,
                                           'rank_badge': '🥈 Peringkat #2 Nasional',
                                           'share': '4,99%',
                                           'syamanah_rev': 'Rp 3,24 M / bln'},
                                          {'badge_class': 'bg-secondary text-white',
                                           'category': 'Jaket & Outerwear Korporat',
                                           'leader': 'PT Pan Brothers Tbk (Rp 8,5 M/bln)',
                                           'rank': 3,
                                           'rank_badge': '🥉 Peringkat #3 Nasional',
                                           'share': '1,73%',
                                           'syamanah_rev': 'Rp 3,24 M / bln (Blended)'},
                                          {'badge_class': 'bg-success text-white',
                                           'category': 'Seragam Kerja PDH/PDL Korporat',
                                           'leader': 'PT Trisula International Tbk (Rp 15,0 M/bln)',
                                           'rank': 4,
                                           'rank_badge': '🎖️ Peringkat #4 Nasional',
                                           'share': '2,59%',
                                           'syamanah_rev': 'Rp 3,24 M / bln'},
                                          {'badge_class': 'bg-primary text-white',
                                           'category': 'Keseluruhan Produsen Apparel B2B Nasional',
                                           'leader': 'PT Pan Brothers Tbk (Rp 18,5 M/bln)',
                                           'rank': 5,
                                           'rank_badge': '🏆 TOP #5 SE-INDONESIA',
                                           'share': '4,77%',
                                           'syamanah_rev': 'Rp 3,24 M / bln'}],
                       'headline': 'TOP #5 PRODUSEN APPAREL B2B NASIONAL SE-INDONESIA',
                       'monthly_revenue_avg': 3242000000,
                       'monthly_revenue_formatted': 'Rp 3,24 Miliar / bln',
                       'national_share_pct': 4.77,
                       'overall_rank': 5,
                       'peak_month_formatted': 'Rp 4,94 Miliar (Juli 2026)',
                       'peak_monthly_revenue': 4942519812,
                       'projected_annual_revenue': 38904000000,
                       'total_market_players': '850+ Produsen & Pabrik Apparel B2B Terdaftar di Indonesia',
                       'total_ranked': 20}}

PDF_BENCHMARK_DATA = B2B_BENCHMARK_DATA


def get_financial_summary() -> Dict[str, Any]:
    """Mengembalikan ringkasan omzet historis dan proyeksi tahunan Syamanah Group."""
    total_syamanah_9mo = sum(m["syamanah"] for m in REVENUE_DATA_2026)
    total_raffiz_9mo = sum(m["raffiz"] for m in REVENUE_DATA_2026)
    total_group_9mo = total_syamanah_9mo + total_raffiz_9mo
    
    # Rata-rata per bulan
    avg_monthly_group = total_group_9mo / len(REVENUE_DATA_2026)
    avg_monthly_syamanah = total_syamanah_9mo / len(REVENUE_DATA_2026)
    
    # Proyeksi 12 bulan (Annualized Run-Rate 2026)
    projected_annual_group = avg_monthly_group * 12
    projected_annual_syamanah = avg_monthly_syamanah * 12

    # Analisis Peak & Low Month
    sorted_by_total = sorted(REVENUE_DATA_2026, key=lambda x: x["total"], reverse=True)
    peak_month = sorted_by_total[0]
    low_month = sorted_by_total[-1]

    return {
        "monthly_breakdown": REVENUE_DATA_2026,
        "total_syamanah_9mo": total_syamanah_9mo,
        "total_raffiz_9mo": total_raffiz_9mo,
        "total_group_9mo": total_group_9mo,
        "avg_monthly_group": avg_monthly_group,
        "projected_annual_group": projected_annual_group,
        "projected_annual_syamanah": projected_annual_syamanah,
        "peak_month": peak_month,
        "low_month": low_month,
    }


def get_market_size_and_share(custom_avg_spend: Optional[int] = None) -> Dict[str, Any]:
    """Menghitung metrik TAM, SAM, SOM, dan Market Share Syamanah Group."""
    fin = get_financial_summary()
    default_spend = custom_avg_spend or 280000  # Default Rp 280.000 / orang / tahun

    # 1. Total Populasi Pasar dari Database Master Organizations
    total_orgs = Organization.query.count()
    total_people = db.session.query(func.sum(Organization.estimated_members)).scalar() or 0

    # 2. SAM: Tier A + B + C (Segmen Relevan Bernilai Tinggi)
    sam_query = Organization.query.filter(
        Organization.priority_tier.in_(["A - HOT", "Tier A", "B - WARM", "Tier B", "C - POTENTIAL", "Tier C"])
    )
    sam_orgs = sam_query.count()
    sam_people = db.session.query(func.sum(Organization.estimated_members)).filter(
        Organization.priority_tier.in_(["A - HOT", "Tier A", "B - WARM", "Tier B", "C - POTENTIAL", "Tier C"])
    ).scalar() or 0

    # 3. SOM: Tier A + B (Target Inti Hot & Warm dengan Peluang Penutupan Transaksi Tertinggi)
    som_query = Organization.query.filter(
        Organization.priority_tier.in_(["A - HOT", "Tier A", "B - WARM", "Tier B"])
    )
    som_orgs = som_query.count()
    som_people = db.session.query(func.sum(Organization.estimated_members)).filter(
        Organization.priority_tier.in_(["A - HOT", "Tier A", "B - WARM", "Tier B"])
    ).scalar() or 0

    # 4. Nilai Moneter Pasar (Market Value in Rupiah & Pcs Apparel)
    avg_price_per_pcs = 140000  # Rata-rata per helai
    pcs_per_person = round(default_spend / avg_price_per_pcs, 1)

    tam_value_rp = total_people * default_spend
    sam_value_rp = sam_people * default_spend
    som_value_rp = som_people * default_spend

    tam_pcs = int(total_people * pcs_per_person)
    sam_pcs = int(sam_people * pcs_per_person)
    som_pcs = int(som_people * pcs_per_person)

    # 5. Pangsa Pasar (Market Share) Syamanah
    annual_revenue = fin["projected_annual_group"]
    ms_tam_pct = round((annual_revenue / tam_value_rp * 100), 2) if tam_value_rp > 0 else 0.0
    ms_sam_pct = round((annual_revenue / sam_value_rp * 100), 2) if sam_value_rp > 0 else 0.0
    ms_som_pct = round((annual_revenue / som_value_rp * 100), 2) if som_value_rp > 0 else 0.0

    # Sisa Pasar Tak Tergarap di SAM (Unaddressed Potential in SAM)
    unaddressed_sam_rp = max(0, sam_value_rp - annual_revenue)
    unaddressed_sam_pct = round(100.0 - min(100.0, ms_sam_pct), 1)

    # 6. Breakdown Potensi Pasar per Kategori Organisasi
    type_breakdown = []
    types_config = [
        ("Perusahaan", ["Perusahaan", "corporate", "company"], "Korporasi & Bisnis PT", "bi-building", "primary", 340000),
        ("Manufaktur", ["Manufaktur", "manufacturing"], "Pabrik & Industri Manufaktur", "bi-gear-wide-connected", "secondary", 340000),
        ("Pendidikan", ["education", "Pendidikan", "school", "university"], "Sekolah & Perguruan Tinggi", "bi-mortarboard", "info", 290000),
        ("Mahasiswa", ["student_organization", "student_org"], "Organisasi Mahasiswa (BEM/UKM)", "bi-people", "warning", 220000),
        ("Komunitas", ["community", "Komunitas Olahraga", "sports_club", "club", "Komunitas Publik"], "Komunitas Olahraga & Publik", "bi-trophy", "success", 200000),
    ]

    for type_key, type_names, label, icon, color, spend in types_config:
        q = Organization.query.filter(Organization.organization_type.in_(type_names))
        cnt = q.count()
        peop = db.session.query(func.sum(Organization.estimated_members)).filter(Organization.organization_type.in_(type_names)).scalar() or 0
        val = peop * spend
        type_breakdown.append({
            "key": type_key,
            "label": label,
            "icon": icon,
            "color": color,
            "org_count": cnt,
            "people_count": peop,
            "market_value_rp": val,
            "market_value_formatted": f"Rp {val / 1e9:.2f} Miliar",
        })

    # 7. Lanskap Kompetisi & Pangsa Pasar (Competitor Breakdown Model)
    # Model representasi pasar apparel B2B Indonesia
    competitor_landscape = [
        {
            "player": "Syamanah Group (Syamanah + Raffiz)",
            "type": "Leading B2B Custom Apparel",
            "share_pct": ms_tam_pct,
            "revenue_rp": annual_revenue,
            "badge_color": "success",
            "is_syamanah": True,
        },
        {
            "player": "Vendor Apparel / Garmen Nasional Lainnya",
            "type": "Kompetitor Korporat Skala Menengah-Besar",
            "share_pct": 24.5,
            "revenue_rp": tam_value_rp * 0.245,
            "badge_color": "warning",
            "is_syamanah": False,
        },
        {
            "player": "Konveksi Lokal & Penjahit Daerah (Fragmented)",
            "type": "Pemain Tradisional / UMKM Daerah",
            "share_pct": round(100.0 - ms_tam_pct - 24.5, 2),
            "revenue_rp": tam_value_rp * (1.0 - (ms_tam_pct / 100.0) - 0.245),
            "badge_color": "secondary",
            "is_syamanah": False,
        },
    ]

    return {
        "tam": {
            "value_rp": tam_value_rp,
            "people": total_people,
            "orgs": total_orgs,
            "pcs": tam_pcs,
            "label": "Total Addressable Market (TAM)",
            "description": "Total seluruh potensi pasar seragam & custom apparel dari 8.559 organisasi master terdata di Indonesia.",
        },
        "sam": {
            "value_rp": sam_value_rp,
            "people": sam_people,
            "orgs": sam_orgs,
            "pcs": sam_pcs,
            "label": "Serviceable Addressable Market (SAM)",
            "description": "Pasar yang relevan dengan lini produk Syamanah (Tier A, Tier B, Tier C yang memiliki kebutuhan apparel tinggi).",
        },
        "som": {
            "value_rp": som_value_rp,
            "people": som_people,
            "orgs": som_orgs,
            "pcs": som_pcs,
            "label": "Serviceable Obtainable Market (SOM)",
            "description": "Pasar sasaran jangka pendek Syamanah (Tier A & B Hot/Warm Leads yang memiliki kontak dan peluang penutupan transaksi tertinggi).",
        },
        "market_share": {
            "vs_som_pct": ms_som_pct,
            "vs_sam_pct": ms_sam_pct,
            "vs_tam_pct": ms_tam_pct,
            "annual_projected_revenue": annual_revenue,
            "actual_9mo_revenue": fin["total_group_9mo"],
            "unaddressed_sam_rp": unaddressed_sam_rp,
            "unaddressed_sam_pct": unaddressed_sam_pct,
        },
        "financials": fin,
        "pricing": PRODUCT_PRICING,
        "type_breakdown": type_breakdown,
        "competitor_landscape": competitor_landscape,
        "benchmarks": PDF_BENCHMARK_DATA,
        "national_top_brands": PDF_BENCHMARK_DATA.get("national_top_brands", []),
        "syamanah_standing": PDF_BENCHMARK_DATA.get("syamanah_standing", {}),
        "assumptions": {
            "spend_per_person": default_spend,
            "avg_price_per_pcs": avg_price_per_pcs,
            "pcs_per_person": pcs_per_person,
        }
    }


def get_syamanah_benchmark_report() -> Dict[str, Any]:
    """Mengembalikan data komprehensif Market Size & Market Share Versi Syamanah
    yang membandingkan realitas internal finansial & 8.559 organisasi dengan data benchmark nasional PDF.
    """
    data = get_market_size_and_share()
    return {
        **data,
        "report_generated_date": "Oktober 2026",
        "company_name": "Syamanah Group",
        "brands": ["Syamanah Apparel (B2B)", "Raffiz (Retail & Quick Order)"],
    }


def simulate_expansion(additional_tier_c_pct: float = 5.0, price_change_pct: float = 0.0) -> Dict[str, Any]:
    """Simulasi skenario bisnis (What-If Analysis):
    Berapa potensi kenaikan omzet jika Syamanah menambah penetrasi di Tier C sebesar X%?
    """
    tier_c_people = db.session.query(func.sum(Organization.estimated_members)).filter(
        Organization.priority_tier.in_(["C - POTENTIAL", "Tier C"])
    ).scalar() or 0
    tier_c_orgs = Organization.query.filter(
        Organization.priority_tier.in_(["C - POTENTIAL", "Tier C"])
    ).count()

    base_spend = 280000 * (1.0 + (price_change_pct / 100.0))
    tier_c_total_market = tier_c_people * base_spend

    # Nilai tambahan omzet yang bisa diraih
    additional_revenue = tier_c_total_market * (additional_tier_c_pct / 100.0)
    additional_people_served = int(tier_c_people * (additional_tier_c_pct / 100.0))
    additional_orgs_served = int(tier_c_orgs * (additional_tier_c_pct / 100.0))

    fin = get_financial_summary()
    current_annual = fin["projected_annual_group"]
    new_annual_projected = current_annual + additional_revenue
    growth_pct = round((additional_revenue / current_annual * 100), 2) if current_annual > 0 else 0.0

    return {
        "additional_tier_c_pct": additional_tier_c_pct,
        "price_change_pct": price_change_pct,
        "tier_c_total_market": tier_c_total_market,
        "additional_revenue": additional_revenue,
        "additional_people_served": additional_people_served,
        "additional_orgs_served": additional_orgs_served,
        "current_annual_revenue": current_annual,
        "new_annual_projected": new_annual_projected,
        "growth_pct": growth_pct,
    }
